<?php

#AUTOGENERATED BY HYBRIDAUTH 2.1.0-dev INSTALLER - Monday 20th of August 2012 09:36:22 AM

/* !
 * HybridAuth
 * http://hybridauth.sourceforge.net | http://github.com/hybridauth/hybridauth
 * (c) 2009-2012, HybridAuth authors | http://hybridauth.sourceforge.net/licenses.html
 */

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------

return array("hauth" =>
    array(
        "base_url" => "http://".$langs = Kohana::$config->load('appconf.main_domain')."/hauth/startlogin",
        "providers" => array(
            // openid providers
            "OpenID" => array(
                "enabled" => false
            ),
            "AOL" => array(
                "enabled" => false
            ),
            "Yahoo" => array(
                "enabled" => false,
                "keys" => array("id" => "", "secret" => "")
            ),
            "Google" => array(
                "enabled" => true,
                "keys" => array("id" => "", "secret" => "")
            ),
            "Facebook" => array(
                "enabled" => true,
                "keys" => array("id" => "", "secret" => "")
            ),

            "Twitter" => array(
                "enabled" => true,
                "keys" => array("key" => "", "secret" => "")
            ),
            // windows live
            "Live" => array(
                "enabled" => false,
                "keys" => array("id" => "", "secret" => "")
            ),
            "MySpace" => array(
                "enabled" => false,
                "keys" => array("key" => "", "secret" => "")
            ),
            "LinkedIn" => array(
                "enabled" => false,
                "keys" => array("key" => "", "secret" => "")
            ),
            "Foursquare" => array(
                "enabled" => false,
                "keys" => array("id" => "", "secret" => "")
            ),
            "Mailru" => array(
                "enabled" => false,
                "keys" => array("id" => "684300", "secret" => "f01895e8a01a76cb5f66fd7d30e5c0f9")
            ),
            "Vkontakte" => array(
                "enabled" => true,
                "keys" => array("id" => "3141662", "secret" => "y32PLBnn4SRyx7VXuJRu")
            )
        ),
        // if you want to enable logging, set 'debug_mode' to true  then provide a writable file by the web server on "debug_file"
        "debug_mode" => false,
        "debug_file" => DOCROOT . 'public/hauth_log'
    )
);

